-- ============================================================
-- VSO 车辆销售订单系统 - 统一订单状态为数值存储
-- Flyway 版本：V1.19.0
-- ============================================================

SET NAMES utf8mb4;

-- 1. 添加新字段 order_state (INT)
ALTER TABLE `vso_order` 
    ADD COLUMN `order_state` INT DEFAULT NULL COMMENT '订单状态数值' AFTER `license_city`;

-- 2. 迁移数据：将 main_status 字符串转换为 order_state 数值
-- OrderState 映射关系：
-- WISHLIST=100, EARNEST_MONEY_UNPAID=200, EARNEST_MONEY_PAID=210
-- DOWN_PAYMENT_UNPAID=300, DOWN_PAYMENT_PAID=310, ARRANGE_PRODUCTION=400
-- ALLOCATION_VEHICLE=450, APPLY_TRANSPORT=470, PREPARE_TRANSPORT=500
-- TRANSPORTING=550, PREPARE_DELIVER=600, FINAL_PAYMENT_PAID=620
-- INVOICED=630, DELIVERED=650, ACTIVATED=700
-- RETURN_APPLY=800, RETURN_STORAGE=820, RETURN_AUDIT=840
-- RETURN_COMPLETED=860, REFUND_APPLY=920, REFUND_COMPLETE=925
-- CANCEL=950, EXPIRED=960
-- MainStatus 映射（旧枚举，需要建立对应关系）
UPDATE `vso_order` SET `order_state` = CASE `main_status`
    WHEN 'PENDING_CREATE' THEN 100
    WHEN 'PENDING_SUBMIT' THEN 200
    WHEN 'PENDING_AUDIT' THEN 200
    WHEN 'PENDING_LOCK' THEN 300
    WHEN 'LOCKED' THEN 400
    WHEN 'PENDING_VEHICLE_ASSIGN' THEN 400
    WHEN 'VEHICLE_ASSIGNED' THEN 450
    WHEN 'PENDING_CONTRACT' THEN 450
    WHEN 'PENDING_PAYMENT' THEN 500
    WHEN 'PENDING_DELIVERY' THEN 600
    WHEN 'DELIVERED' THEN 650
    WHEN 'COMPLETED' THEN 700
    WHEN 'CANCELLED' THEN 950
    WHEN 'CLOSED' THEN 960
    WHEN 'WISHLIST' THEN 100
    WHEN 'EARNEST_MONEY_UNPAID' THEN 200
    WHEN 'EARNEST_MONEY_PAID' THEN 210
    WHEN 'DOWN_PAYMENT_UNPAID' THEN 300
    WHEN 'DOWN_PAYMENT_PAID' THEN 310
    WHEN 'ARRANGE_PRODUCTION' THEN 400
    WHEN 'ALLOCATION_VEHICLE' THEN 450
    WHEN 'APPLY_TRANSPORT' THEN 470
    WHEN 'PREPARE_TRANSPORT' THEN 500
    WHEN 'TRANSPORTING' THEN 550
    WHEN 'PREPARE_DELIVER' THEN 600
    WHEN 'FINAL_PAYMENT_PAID' THEN 620
    WHEN 'INVOICED' THEN 630
    WHEN 'DELIVERED' THEN 650
    WHEN 'ACTIVATED' THEN 700
    WHEN 'RETURN_APPLY' THEN 800
    WHEN 'RETURN_STORAGE' THEN 820
    WHEN 'RETURN_AUDIT' THEN 840
    WHEN 'RETURN_COMPLETED' THEN 860
    WHEN 'REFUND_APPLY' THEN 920
    WHEN 'REFUND_COMPLETE' THEN 925
    WHEN 'CANCEL' THEN 950
    WHEN 'EXPIRED' THEN 960
    ELSE NULL
END;

-- 3. 添加新字段 previous_order_state (INT)
ALTER TABLE `vso_order` 
    ADD COLUMN `previous_order_state` INT DEFAULT NULL COMMENT '关闭前上一有效状态数值' AFTER `order_state`;

-- 4. 迁移 previous_main_status 数据
UPDATE `vso_order` SET `previous_order_state` = CASE `previous_main_status`
    WHEN 'PENDING_CREATE' THEN 100
    WHEN 'PENDING_SUBMIT' THEN 200
    WHEN 'PENDING_AUDIT' THEN 200
    WHEN 'PENDING_LOCK' THEN 300
    WHEN 'LOCKED' THEN 400
    WHEN 'PENDING_VEHICLE_ASSIGN' THEN 400
    WHEN 'VEHICLE_ASSIGNED' THEN 450
    WHEN 'PENDING_CONTRACT' THEN 450
    WHEN 'PENDING_PAYMENT' THEN 500
    WHEN 'PENDING_DELIVERY' THEN 600
    WHEN 'DELIVERED' THEN 650
    WHEN 'COMPLETED' THEN 700
    WHEN 'CANCELLED' THEN 950
    WHEN 'CLOSED' THEN 960
    WHEN 'WISHLIST' THEN 100
    WHEN 'EARNEST_MONEY_UNPAID' THEN 200
    WHEN 'EARNEST_MONEY_PAID' THEN 210
    WHEN 'DOWN_PAYMENT_UNPAID' THEN 300
    WHEN 'DOWN_PAYMENT_PAID' THEN 310
    WHEN 'ARRANGE_PRODUCTION' THEN 400
    WHEN 'ALLOCATION_VEHICLE' THEN 450
    WHEN 'APPLY_TRANSPORT' THEN 470
    WHEN 'PREPARE_TRANSPORT' THEN 500
    WHEN 'TRANSPORTING' THEN 550
    WHEN 'PREPARE_DELIVER' THEN 600
    WHEN 'FINAL_PAYMENT_PAID' THEN 620
    WHEN 'INVOICED' THEN 630
    WHEN 'DELIVERED' THEN 650
    WHEN 'ACTIVATED' THEN 700
    WHEN 'RETURN_APPLY' THEN 800
    WHEN 'RETURN_STORAGE' THEN 820
    WHEN 'RETURN_AUDIT' THEN 840
    WHEN 'RETURN_COMPLETED' THEN 860
    WHEN 'REFUND_APPLY' THEN 920
    WHEN 'REFUND_COMPLETE' THEN 925
    WHEN 'CANCEL' THEN 950
    WHEN 'EXPIRED' THEN 960
    ELSE NULL
END;

-- 5. 更新索引
ALTER TABLE `vso_order` DROP INDEX `idx_status_time`;
ALTER TABLE `vso_order` DROP INDEX `idx_store_sales_status`;
ALTER TABLE `vso_order` ADD INDEX `idx_status_time` (`order_state`, `created_at_business`);
ALTER TABLE `vso_order` ADD INDEX `idx_store_sales_status` (`store_code`, `sales_code`, `order_state`);

-- 6. 同步修改影子删除表
ALTER TABLE `vso_order_shadow_delete` 
    ADD COLUMN `before_order_state` INT DEFAULT NULL COMMENT '删除前订单状态数值' AFTER `delete_reason`;

UPDATE `vso_order_shadow_delete` SET `before_order_state` = CAST(`before_main_status` AS SIGNED);

-- 7. 删除旧字段（可选：先保留一段时间再删除，这里先注释）
-- ALTER TABLE `vso_order` DROP COLUMN `main_status`;
-- ALTER TABLE `vso_order` DROP COLUMN `previous_main_status`;
-- ALTER TABLE `vso_order_shadow_delete` DROP COLUMN `before_main_status`;